### ISSUE TITLE
[Android] [arm64] First application launch crash

### ISSUE THREAD

**Issue by huran438** [devtodev-analytics/unity-sdk#12]
Spec:
- Unity3D 2018.4f1
- D2D 1.12.1
- Android 9 (Xiaomi Mi A1)

After first launch of application its instantly crashes (before logo). On next launches its working as expected (without crash)

Log:
`Caused by java.lang.RuntimeException: Unable to instantiate service com.devtodev.push.firebase.DTDFcmMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.devtodev.push.firebase.DTDFcmMessagingService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/base.apk", zip file "/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/lib/arm64, /data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/base.apk!/lib/arm64-v8a, /data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3531)
       at android.app.ActivityThread.access$1300(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

`Caused by java.lang.ClassNotFoundException: Didn't find class "com.devtodev.push.firebase.DTDFcmMessagingService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/base.apk", zip file "/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/lib/arm64, /data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/base.apk!/lib/arm64-v8a, /data/app/studio.secretplace.ttf--ZIbQUAnxp4rRy6_3wcgIQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3526)
       at android.app.ActivityThread.access$1300(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by Skazochnij** [comment]
Hello, please make sure the following dependencies are along the path /Assets/Plugins/Android:
 - com.google.firebase.firebase-messaging-XXX
 - com.google.firebase.firebase-iid-XXX

**Comment by huran438** [comment]
Its working now. But only when i'm integrating firebase messaging sdk.

P.S. We have other firebase sdks integrated in our project: analytics + crashlytics

**Comment by Skazochnij** [comment]
Unfortunately, at the moment when integrating our sdk, it is necessary to pull dependencies for the push notifications, regardless of notifications are used or not. We are aware of this issue and will solve it in future releases.
