### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by KostyaChoporov** [devtodev-analytics/unity-sdk#3]
Hi, we found rare issue on android, it appears only on android 4.2

```
java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.5.2f1
Device model      : Lenovo Lenovo A5500-F
Device fingerprint: Lenovo/A5500-F/A5500-F:4.2.2/JDQ39/A5500F_A422_000_024_140328_ROW:user/release-keys

Caused by: java.lang.NoSuchMethodError: org.json.JSONArray.remove
	at com.devtodev.core.utils.SessionInformation.removeSessionDataNative(SessionInformation.java:116)
	at com.devtodev.core.utils.SessionInformation.access$000(SessionInformation.java:14)
	at com.devtodev.core.utils.SessionInformation$1.OnSend(SessionInformation.java:77)
	at com.devtodev.core.utils.CoreAsyncTask.onPostExecute(CoreAsyncTask.java:68)
	at com.devtodev.core.utils.CoreAsyncTask.onPostExecute(CoreAsyncTask.java:10)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5370)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
```

What it can be

**Comment by Skazochnij** [comment]
Hello, we fix it in [2.4.2](https://github.com/devtodev-analytics/unity-sdk/releases/tag/v2.4.2) version
