### ISSUE TITLE
Android Unity game crashes during d2d initializing (Unity 2018.2.1f1)

### ISSUE THREAD

**Issue by sshumihin** [devtodev-analytics/unity-sdk#8]
Reproduced on a blank project. D2d v. 2.8.1

Log message from Logcat:
```
07-30 15:12:48.490 21660-21739/net.infoshell.mygame I/Unity: [DevToDev] 2018/07/30 15:12:48 : Initializing sdk with key MY_KEY and version 2.8.1
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    DevToDev.Core.Utils.Log:R(String, Object[])
    DevToDev.Core.Utils.Log:R(String)
    DevToDev.Logic.SDKClient:Initialize(String, String)
    DevToDev.Analytics:Initialize(String, String)
    DTDEditor.DevToDevSDK:InitializeAnalytics(DTDPlatform) (at F:\Assets\devtodev\Window\DevToDevSDK.cs:61)
    DTDEditor.DevToDevSDK:Start() (at F:\Assets\devtodev\Window\DevToDevSDK.cs:33)
     
    (Filename: F Line: 0)
07-30 15:12:48.680 21660-21739/net.infoshell.mygame E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Verizon/zerofltevzw/zerofltevzw:5.1.1/LMY47X/G920VVRU3BOG5:user/release-keys'
    Revision: '10'
    pid: 21660, tid: 21739, name: UnityMain  >>> net.infoshell.mygame <<<
        r0 00000000  r1 00000000  r2 00000001  r3 00000000
        r4 ddd59f10  r5 00000000  r6 00100e7e  r7 f4994b21
        r8 d5dd1898  r9 00000000  sl d60bd35c  fp ddd59f50
        ip df85b03c  sp ddd59e90  lr ddf2b710  pc f7399f00  cpsr ef101c90
    backtrace:
07-30 15:12:49.090 21660-21739/net.infoshell.mygame E/CRASH: 	#00  pc 00014f00  /system/lib/libc.so (strlen+83)
    	#01  pc 001d070c  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (AndroidJNIBindingsHelpers::CallStaticStringMethod(void*, void*, dynamic_array<jvalue, 0u> const&)+292)
    	#02  pc 001d6b70  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (AndroidJNI_CUSTOM_CallStaticStringMethod(void*, void*, MonoArray*)+124)
    	#03  pc 00008354   ( (wrapper managed-to-native) UnityEngine.AndroidJNI:CallStaticStringMethod (intptr,intptr,UnityEngine.jvalue[]) + 0x84 (0xd6e622d0 0xd6e623d4) [0xef035ee0 - Unity Root Domain]+33620)
    	#04  il ........  at (wrapper managed-to-native) UnityEngine.AndroidJNI.CallStaticStringMethod (intptr,intptr,UnityEngine.jvalue[]) <IL 0x00023, 0xffffffff>
    	#05  il 000000c4  at UnityEngine.AndroidJNISafe.CallStaticStringMethod (intptr,intptr,UnityEngine.jvalue[]) [0x00005] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:213
    	#06  il 00000be7  at UnityEngine.AndroidJavaObject._CallStatic<object> (string,object[]) [0x00244] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:447
    	#07  il 000000cf  at UnityEngine.AndroidJavaObject.CallStatic<object> (string,object[]) [0x00004] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJava.bindings.cs:91
    	#08  il 000000bb  at DevToDev.Core.Serialization.NativeDataLoaderPlatform.Load (string) <IL 0x00019, 0x000bb>
    	#09  il 0000018b  at DevToDev.Logic.Cross.UsersStorage.LoadNative () <IL 0x0002c, 0x0018b>
    	#10  il 00000177  at DevToDev.Logic.SDKClient.get_UsersStorage () <IL 0x00030, 0x00177>
    	#11  il 000003ab  at DevToDev.Logic.SDKClient.Initialize (string,string) <IL 0x0008a, 0x003ab>
    	#12  il 00000073  at DevToDev.Analytics.Initialize (string,string) <IL 0x00007, 0x00073>
    	#13  il 0000020f  at DTDEditor.DevToDevSDK.InitializeAnalytics (DTDEditor.DTDPlatform) [0x00039] in F:\\Assets\devtodev\Window\DevToDevSDK.cs:61
    	#14  il 00000147  at DTDEditor.DevToDevSDK.Start () [0x00016] in F:\\Assets\devtodev\Window\DevToDevSDK.cs:33
    	#15  il 0000013b  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <IL 0x0001c, 0x0013b>
    	#00  pc 000225d3  /data/app/net.infoshell.mygame -2/lib/arm/libmono.so
    	#01  pc 001f7bb8  /data/app/net.infoshell.mygame -2/lib/arm/libmono.so (mono_runtime_invoke+136)
    	#02  pc 00fb7ea4  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)+84)
    	#03  pc 00dc6ab0  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingExceptionPtr*)+1336)
    	#04  pc 00dc6b40  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr)+68)
    	#05  pc 00dc5abc  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (MonoBehaviour::DelayedStartCall(Object*, void*)+76)
    	#06  pc 00a2e924  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (DelayedCallManager::Update(int)+500)
    	#07  pc 00d9ae90  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (InitPlayerLoopCallbacks()::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward()+60)
    	#08  pc 00d9bc54  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)+96)
    	#09  pc 00d9bca4  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)+176)
    	#10  pc 00d9be4c  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (PlayerLoop()+284)
    	#11  pc 0061ba60  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (UnityPlayerLoop()+572)
    	#12  pc 0061f1a4  /data/app/net.infoshell.mygame -2/lib/arm/libunity.so (nativeRender(_JNIEnv*, _jobject*)+52)
    	#13  pc 0062e84f  /data/dalvik-cache/arm/data@app@net.infoshell.mygame -2@base.apk@classes.dex
    memory near r6:
        00100e5c ffffffff ffffffff ffffffff ffffffff  ................
07-30 15:12:49.100 21660-21739/net.infoshell.mygame E/CRASH:     00100e6c ffffffff ffffffff ffffffff ffffffff  ................
        00100e7c ffffffff ffffffff ffffffff ffffffff  ................
        00100e8c ffffffff ffffffff ffffffff ffffffff  ................
        00100e9c ffffffff ffffffff ffffffff ffffffff  ................
        00100eac ffffffff ffffffff ffffffff ffffffff  ................
        00100ebc ffffffff ffffffff ffffffff ffffffff  ................
        00100ecc ffffffff ffffffff ffffffff ffffffff  ................
        00100edc ffffffff ffffffff ffffffff ffffffff  ................
        00100eec ffffffff ffffffff ffffffff ffffffff  ................
        00100efc ffffffff ffffffff ffffffff ffffffff  ................
        00100f0c ffffffff ffffffff ffffffff ffffffff  ................
        00100f1c ffffffff ffffffff ffffffff ffffffff  ................
        00100f2c ffffffff ffffffff ffffffff ffffffff  ................
        00100f3c ffffffff ffffffff ffffffff ffffffff  ................
        00100f4c ffffffff ffffffff ffffffff ffffffff  ................
    code around pc:
        f7399ee0 b31a2b01 0f04f013 800af000 3b04f851  .+..........Q..;
        f7399ef0 3c01f1a3 0c03ea2c 3c80f01c 8033f040  ...<,......<@.3.
        f7399f00 2302e8f1 f040f891 3c01f1a2 0c02ea2c  ...#..@....<,...
        f7399f10 3c80f01c 800ff040 3c01f1a3 0c03ea2c  ...<@......<,...
        f7399f20 3c80f01c 801ff040 bfeaf7ff 0000eba1  ...<@...........
        f7399f30 0001f1a0 eba14770 ea5f0000 f040434c  ....pG...._.LC@.
        f7399f40 f0808009 ea5f800a f0400c4c f1a08009  ......_.L.@.....
        f7399f50 47700005 0008f1a0 f1a04770 47700007  ..pG....pG....pG
        f7399f60 0006f1a0 eba14770 ea5f0000 f040434c  ....pG...._.LC@.
        f7399f70 f0808009 ea5f800a f0400c4c f1a08009  ......_.L.@.....
        f7399f80 47700001 0004f1a0 f1a04770 47700003  ..pG....pG....pG
        f7399f90 0002f1a0 bf004770 00000000 00000000  ....pG..........
        f7399fa0 00000000 00000000 00000000 00000000  ................
        f7399fb0 00000000 00000000 00000000 00000000  ................
        f7399fc0 e1a0c000 e1a00001 e1a0100c e050c001  ..............P.
        f7399fd0 012fff1e 8152000c 9affea31 e52d0004  ../...R.1.....-.
    code around lr:
        ddf2b6f0 e5841014 edd00b00 e5900008 e5840020  ............ ...
        ddf2b700 edc40b06 e5c41004 e3a00000 ebfaf3a9  ................
        ddf2b710 e1a02000 e1a00004 e3a01000 eb00ad50  . ..........P...
        ddf2b720 e5dd0008 e3500000 0a000003 eb10dcd8  ......P.........
        ddf2b730 e5901000 e5911014 e12fff31 e59f0194  ........1./.....
        ddf2b740 e59d1034 e79f0000 e5900000 e0500001  4.............P.
        ddf2b750 028dd038 08bd81f0 ebfaf393 e59d000c  8...............
        ddf2b760 e3a02000 e3a07000 e5901000 e59132a4  . ...p.......2..
        ddf2b770 e1a01005 e12fff33 e1a06000 e3560000  ....3./..`....V.
        ddf2b780 0a000005 e59d000c e5901000 e5911390  ................
        ddf2b790 e12fff31 e3500000 0a000014 e59d000c  1./...P.........
        ddf2b7a0 e1a02006 e5901000 e59132a8 e1a01005  . .......2......
        ddf2b7b0 e12fff33 e59d000c e5901000 e591205c  3./.........\ ..
        ddf2b7c0 e1a01005 e12fff32 e59f00f8 e5847000  ....2./......p..
        ddf2b7d0 e5847014 e79f0000 edd00b00 e5900008  .p..............
        ddf2b7e0 e5840020 edc40b06 e5c47004 eaffffc5   ........p......
07-30 15:12:49.100 21660-21739/net.infoshell.mygame A/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    Build fingerprint: 'Verizon/zerofltevzw/zerofltevzw:5.1.1/LMY47X/G920VVRU3BOG5:user/release-keys'
    Revision: '10'
    pid: 21660, tid: 21739, name: UnityMain  >>> net.infoshell.mygame <<<
        r0 00000000  r1 00000000  r2 00000001  r3 00000000
        r4 ddd59f10  r5 00000000  r6 00100e7e  r7 f4994b21
        r8 d5dd1898  r9 00000000  sl d60bd35c  fp ddd59f50
        ip df85b03c  sp ddd59e90  lr ddf2b710  pc f7399f00  cpsr ef101c90
    
        at libc.strlen(strlen:83)
        at libunity.AndroidJNIBindingsHelpers::CallStaticStringMethod(void*, void*, dynamic_array<jvalue, 0u> const&)(CallStaticStringMethod:292)
        at libunity.AndroidJNI_CUSTOM_CallStaticStringMethod(void*, void*, MonoArray*)(AndroidJNI_CUSTOM_CallStaticStringMethod:124)
        at Unknown.00008354(Unknown Source)
        at AndroidJNI.CallStaticStringMethod(Native Method)
        at AndroidJNISafe.CallStaticStringMethod(AndroidJNISafe.cs:213)
        at AndroidJavaObject._CallStatic(AndroidJavaImpl.cs:447)
        at AndroidJavaObject.CallStatic(AndroidJava.bindings.cs:91)
        at NativeDataLoaderPlatform.Load(<0x000bb>:187)
        at UsersStorage.LoadNative(<0x0018b>:395)
        at SDKClient.get_UsersStorage(<0x00177>:375)
        at SDKClient.Initialize(<0x003ab>:939)
        at Analytics.Initialize(<0x00073>:115)
        at DevToDevSDK.InitializeAnalytics(DevToDevSDK.cs:61)
        at DevToDevSDK.Start(DevToDevSDK.cs:33)
        at Object.runtime_invoke_void__this__(Native Method)
        at libmono.000225d3(Native Method)
        at libmono.mono_runtime_invoke(mono_runtime_invoke:136)
        at libunity.ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)(Invoke:84)
        at libunity.MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingExceptionPtr*)(InvokeMethodOrCoroutineChecked:1336)
        at libunity.MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr)(InvokeMethodOrCoroutineChecked:68)
        at libunity.MonoBehaviour::DelayedStartCall(Object*, void*)(DelayedStartCall:76)
        at libunity.DelayedCallManager::Update(int)(Update:500)
        at libunity.InitPlayerLoopCallbacks()::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward()(InitPlayerLoopCallbacks:60)
        at libunity.ExecutePlayerLoop(NativePlayerLoopSystem*)(ExecutePlayerLoop:96)
        at libunity.ExecutePlayerLoop(NativePlayerLoopSystem*)(ExecutePlayerLoop:176)
        at libunity.PlayerLoop()(PlayerLoop:284)
        at libunity.UnityPlayerLoop()(UnityPlayerLoop:572)
        at libunity.nativeRender(_JNIEnv*, _jobject*)(nativeRender:52)
        at data@app@net.0062e84f(Native Method)
07-30 15:12:53.470 21660-21727/net.infoshell.mygame W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/net.infoshell.mygame /files/AppEventsLogger.persistedevents
```
Please, fix it asap.

**Comment by Skazochnij** [comment]
Good afternoon, this problem has appeared with a new release, and at the moment we are working on a solution.

https://issuetracker.unity3d.com/issues/android-androidjavaobject-dot-call-crashes-with-fatal-signal-11-sigsegv

**Comment by sshumihin** [comment]
Thank you, man.

**Comment by Skazochnij** [comment]
We add support of Unity 2018.2 in [v2.9](https://github.com/devtodev-analytics/unity-sdk/releases/tag/v2.9) Please update to that.
